changelog:
  categories:
    - title: '🚀 Features'
      labels:
        - 'feature'
        - 'enhancement'

    - title: '🐛 Bug Fixes'
      labels:
        - 'bug'
        - 'fix'

    - title: '🧰 Maintenance'
      labels:
        - 'refactor'
        - 'maintenance'
        - 'deps'

    - title: '🔍 Other Changes'
      labels: []
