name: Pre-commit Hooks

on: [ pull_request, workflow_dispatch ]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install pre-commit
        uses: actions/setup-python@v3

      - name: Run pre-commit on all files
        uses: pre-commit/action@v3.0.1
