name: Run Collibra Adaptor Sandbox pull request

on: [ pull_request, workflow_dispatch ]

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

jobs:
  run-open-rag-pull-request-check:
    runs-on: ubuntu-latest
    environment: main
    container:
      image: adgonrodr/github-actions-terraform-python:latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.PERSONAL_GITHUB_TOKEN }}

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 - --version 1.4.0
          echo "/github/home/.local/bin" >> $GITHUB_PATH

      - name: Configure Poetry and Install Dependencies
        run: |
          poetry config virtualenvs.create false
          poetry install

      - name: Test Open RAG
        run: |
          bash scripts/build_and_test.sh
        shell: bash
